### PR TITLE
Adding buckled example, removing MPI charge distribution error.

### PR DESCRIPTION
**Pull request by nbrunk**
Adding requested uncharged, buckled icosahedron example.  Also implementing the uniform random seed in the charge distribution scheme thought to have been introduced previously.

### CODE REVIEW

**Comment by nbrunk** [comment]
@jadhao This has been tested and the code changes are trivial.  Mostly just adding example.

Please approve

**Comment by nbrunk** [comment]
@jadhao Please approve

**Comment by jadhao** [comment]
@nbrunk showing conflicts with this PR, not letting approve.  Something related to readme:
<<<<<<< master
=======
* Note that minor changes on order of a percent are expected due to shuffling of the initial charge distributions dependent on different machines' random seed.
* For testing a higher resolution grid (D = 8), use
```time ./np_shape_lab -R 10 -q 600 -c 0.005 -t 1 -v 1 -b 40 -s 40 -S 25000 -D 8 -F n```
>>>>>>> master

Please fix.

**Comment by nbrunk** [comment]
@jadhao I think I've fixed it, it says "no conflicts" now.  I used the website to edit my fork's README, maybe that messed it up.  Should be resolved now.

**Pull request merged**
