### PR TITLE
Adding stripe charge pattern functionality.

### PR DESCRIPTION
**Pull request by nbrunk**
This adds functionality for charged stripe patterns via a boost paramter "N" used previously for the number of stripes.  Janus corresponds to (N = 2), for which you can also specify the relative size of the charged patch via paramter "p", e.g. standard Janus being "-N 2 -p 0.5".

You can now specify up to N = 6, where all values N > 2 assume uniform area patches, e.g. if there are 6 patches each has a the total number of vertices / 6, Nv/6 per patch.  So for N != 2, the "p" paramter does not matter.  

This has been tested against the disc control to ensure "N = 1" simulations weren't affected:

Capture

### CODE REVIEW

**Comment by nbrunk** [comment]
@jadhao Can discuss this shortly, seems ready.

**Comment by nbrunk** [comment]
@jadhao This push along with the new default commands (BOOST flag 'F' for controlling randomness) should eliminate variation from run to run.  

"... -F n"  will give no randomness, neither between machine or with respect to launch time.

"... -F y" will give randomness with respect to the launch time.

This has not been tested on different machines yet, but all processes leading to the charge allocation (I believe the only random variation remaining) are deterministic and internal now.

**Comment by jadhao** [comment]
@nbrunk tested the new no randomness results, it is matching with yours; thanks for clear instructions
tested the stripe functionality with N = 1, seems to give the normal disc
approving
@kadupitiya I suggest you clone this version with no randomness data in examples/ and check to match against future updates. @nbrunk when you request PR ask kadupitiya to review it in addition to me, so he can double check and approve the PR

**Comment by kadupitiya** [comment]
@jadhao: I will clone this version.
Thanks

**Pull request merged**
