### PR TITLE
Optimizing geometric computations, finalizing import of external charge patterns.

### PR DESCRIPTION
**Pull request by nbrunk**
This optimizes the face and vertex geometric functions (compute area, normals, etc.) used primarily within the "dressup" function each step.

This also finalizes necessary functionality for importing external charge patterns specified in a file within the "infiles" folder.  The format of these files is such that column 1 is the vertex index, column 2 is its reduced charge, which is then multiplied by (q), e.g. (q = 600e).  The name of the file is specified via the boost parameter "-E", which has a default of "None" for which the charge is then assigned using internal functions.

This also removes the per-step energy calculation done for the first 1000 steps that has been used thus far in favor of just compting energies once every 500 steps throughout the simulation.   This means the example files are being updated.  The control has worked though, they were the same other than the **dump frequency change**:

Capture

### CODE REVIEW

**Comment by nbrunk** [comment]
Note that this doesn't yet address the Vertex function "compute_area_normals", for which I have left the order the same as it was previously (just grouped the functions "computearea" and "computenormal").

However, I think the area should be computed **before** the normals, since the vertex normals are area-weighted and use this number.  (Although I'm not sure yet where vertex normals are being used.)

**Comment by nbrunk** [comment]
@kadupitiya Please test.

@jadhao Please approve.  This is about 50% speedup locally with 3-8.

**Comment by jadhao** [comment]
@nbrunk @kadupitiya approving. But I suggest dumping every 1000 as 500 is too quick (unless there is a specific reason)? Also, the examples are different than what I get in outfiles after a test run for the kE. Its not much, but in examples it is 0 (for the disc). But I get a very tiny value on the run. Please check.

**Comment by nbrunk** [comment]
@kadupitiya I've tested it on BR2.

@jadhao Locally it gives exactly zero initial temperature and kinetic energy, which was used to give the example files (from Windows).  On Big Red II (from Linux), this is registered as ~10^-307 for the kinetic and ~10^-310 for the temperature.  These are effectively zero and result in completely zero change in all other local quantites.  Specifically, I've checked local {bending, ES, area stretching, surface tension, and volume} along with the global net energy.  Nothing is effected by that change as they are all identical to all decimal places.  Probably just a response to change in machine precision or something.

**Comment by kadupitiya** [comment]
@nbrunk: Thank you so much. I tested on BigRED 2 and it is giving those small values very near zero. It should be ok.

**Pull request merged**
