### PR TITLE
[Draft] Integration tests

### PR DESCRIPTION
**Pull request by supunkamburugamuve**

### CODE REVIEW

**Comment by supunkamburugamuve** [comment]
@kadupitiya it seems these integration tests are taking too much time to run in the travis VM. Would you be able provide some alternative configurations to speed things up?

**Comment by kadupitiya** [comment]
@jadhao: The current integration test uses the following:
args= "np_shape_lab -R 10 -q 600 -c 0.005 -t 1 -v 1 -b 40 -s 40 -S 25000 -D 4 -F n"
Would you recommend changing the number of steps lower than 25000?
@supunkamburugamuve: The only way I can think is lowering the steps. Let's see what @jadhao says.

**Comment by jadhao** [comment]
@supunkamburugamuve @kadupitiya how much time are the tests taking per job? D=4 parameter means a very small grid, so this should be quick for 25000 steps. i want to get a sense of how fast you need the job to run.

**Comment by supunkamburugamuve** [comment]
@kadupitiya when I run these tests on my local machine they run faster. I believe they are using OpenMP to use all the cores. But in these virtual machines, there is a single core.

**Comment by jadhao** [comment]
@supunkamburugamuve @kadupitiya yes, they use openmps. however even on single core, the time should be small for the string of parameters. How much time is it taking on a single VM/core? Also, it will be good to confirm that meaningful output is being produced in the outfiles, sometimes if the simulation breaks down, it can show that its still running but it is just producing garbage (NaN)

**Comment by supunkamburugamuve** [comment]
@jadhao I think one test should complete in about 5~6 minutes maximum on a single-core machine. We have five test cases, so we can target a test time of less than an hour.

**Comment by supunkamburugamuve** [comment]
@jadhao will try on a single core and see how much they take.

**Comment by jadhao** [comment]
@supunkamburugamuve the test with args= "np_shape_lab -R 10 -q 600 -c 0.005 -t 1 -v 1 -b 40 -s 40 -S 25000 -D 4 -F n" should definitely finish in < 5 mins on a reasonably modern single core. I am surprised it is not doing so. can you give me an idea of how long is it taking. like 1 hour or 10 mins?

**Comment by supunkamburugamuve** [comment]
This configuration only tool 3 minutes with a single core. 

./np_shape_lab -R 10 -q 600 -N 2 -p 0.5 -c 0.005 -t 1 -v 1 -b 40 -s 40 -S 25000 -D 4 -F n -H y

The test has been running since yesterday. I cannot see the Travis log to see what is going on exactly.

**Comment by jadhao** [comment]
@supunkamburugamuve 3 mins sounds about right. hmm, not sure why travis is taking long. could be an issue in the sequence of jobs up for testing, like one of them is pathological for some reason (e.g., bad parameter selection, simulation explodes)..

**Comment by supunkamburugamuve** [comment]
Is it possible to restart the build?

**Comment by supunkamburugamuve** [comment]
Closing this pull to create a new one

**Pull request closed without merging**
