### PR TITLE
Initial structure for unit testing

### PR DESCRIPTION
**Pull request by supunkamburugamuve**
This pull request adds a test script to run tests using testbook Python package and a few unit test cases. The build seems to be failing and needs to check why it is failing.

### CODE REVIEW

**Review by jadhao — COMMENTED** [review]
@kadupitiya does this seem reasonable? does not affect anything in src/ files it seems?

**Comment by jadhao** [comment]
@supunkamburugamuve happy to merge after i get some input form kadupitiya. is the build failing on a simple non-parallelized version of the code or the full openmp/mpi code?

**Comment by kadupitiya** [comment]
@jadhao: yes, this will not change anything in our workflow or in nanoHUB integration. Please approve.

**Comment by jadhao** [comment]
@kadupitiya @supunkamburugamuve approving

**Pull request merged**
