### PR TITLE
yinyang function added

### PR DESCRIPTION
**Pull request by fanbsun**
temporary yinyang code

### CODE REVIEW

**Comment by jadhao** [comment]
@nbrunk nick, please review the PR from fanbo on yin yang..looks good to me. please test if previous codes have not broken down

**Comment by fanbsun** [comment]
@jadhao I have updated the readme file, can you see the change or I have to merge the branches?

**Comment by jadhao** [comment]
@fanbsun i can see the change. but there is a conflict due to the readme file. not sure why. can you delete the PR request for readme change. I will approve your first PR on code change, and then you can do another PR on readme later.

**Comment by fanbsun** [comment]
@jadhao I only have one pull request right now and the readme change is inside the "yinyang function added" pull request thread. I don't know how to delete that and might need help with it.

**Comment by jadhao** [comment]
@fanbsun i deleted the readme changes, approving the rest. @nbrunk please check when you get time whether the code is working fine -- i think it is. 
@fanbsun you can proceed with further testing as discussed. and also plus / minus on simple janus pattern or polyhedral patch pattern

**Comment by nbrunk** [comment]
@fanbsun @jadhao This seems reasonable.  Witty to use a trig function of the x argument.  I would add a Boost parameter for the "functionFlag" with a description of what it does to the initial part of main.cpp where the other Boost parameters are defined.  This is good for batch analysis of these jobs.

**Comment by nbrunk** [comment]
@fanbsun @jadhao When I make a code change, at least significant ones, I run at least one of the examples (from the README) to compare the time-series of a few quantities of interest both before-and-after, so maybe compare the electrostatic energy dip and the area over a 25K timestep run.  I automate checking of most of the quantities of interest, but that's unnecssary - I'd recommend just automating or at least visually checking the before-and-after for one example, though.

**Pull request merged**
