### PR TITLE
Fixing warnings, drift cancellation issues, improving stability.

### PR DESCRIPTION
**Pull request by nbrunk**
This removes warnings printed when compiling on Linux systems.  

Additionally, this fixes a bug in the job cancellation code to improve stability as I explained in person.  The simulation now correctly computes the net energy drift and does not immediately abort upon drift greater than 5%, instead aborting after 10 write intervals that violate this criterion (e.g. default 500, so 5000 steps later typically)  This allows observation of what's happening prior to job termination.

This also introduces a "net_Energy_Drift.dat" output file that provides the time evolution of the net energy, the initial energy (to ensure its constant), and the ratio (drift).

The example files are being updated.

### CODE REVIEW

**Comment by nbrunk** [comment]
@kadupitiya @jadhao I've tested this locally and on my account on Big Red II.  Feel free to re-check if you like.  Only that initial discrepancy in kinetic energy and temperature exists between CLion vs. Linux.

@jadhao Please approve.  This introduces no warnings, resolves stability issue.

**Comment by nbrunk** [comment]
@jadhao @kadupitiya I've tested this locally with OMP and on the cluster with both OMP/MPI.  I've tested it for all 3 shapes with 3-4 and the disc control for 3-8.  Feel free to retest, though.

@jadhao This resolves the faulty abort call issue in addition to fixing some warnings and other convenience changes.  The Cpp-computed drift agrees with that computed from the energy output itself when calculated in Mathematica.  I've decided to keep the abort call given I've added a generous abort counter to observe the divergence (10x the write duration, so 5000 steps here).  I will watch closely to ensure it's not a problem later on.

**Comment by nbrunk** [comment]
@jadhao Please approve.

**Comment by jadhao** [comment]
@nbrunk @kadupitiya approving as I did an early pre-test, will check later

**Pull request merged**
