### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kadupitiya**
@jadhao: Testing Travis CI.

### CODE REVIEW

**Review by jadhao — COMMENTED** [review]
@kadupitiya please remove the period at the end

**Review by jadhao — APPROVED** [review]
@kadupitiya approved

**Comment by kadupitiya** [comment]
@jadhao: All the tests are passed now.

**Comment by jadhao** [comment]
@kadupitiya great! I am approving @supunkamburugamuve thanks for setting this up!

**Pull request merged**
